'use strict';
// Design-only fixtures. No persistence, OCR, auth, payments or financial engine.
const screens = [
 ['splash','Splash','Start','A brief brand moment, with no artificial delay.'],
 ['welcome','Welcome','Start','A useful promise and a clear path without an account.'],
 ['initial','Initial onboarding','Setup','Start with JMD and local use. Optional backup comes later.'],
 ['payday','Payday frequency','Setup','Every two weeks and twice monthly are separate choices.'],
 ['next','Next payday','Setup','An explicit date anchors the plan. Irregular income uses a planning date.'],
 ['income','Income setup','Setup','Take-home pay is the default. Future income never becomes actual money automatically.'],
 ['allocation','50/30/20 setup','Setup','A starting point, with freedom to change it.'],
 ['custom','Custom allocation','Setup','Exactly 100%, with a visible rebalancing preview.'],
 ['bills','Bills onboarding','Setup','Bills are optional to enter now; show what reserves would protect.'],
 ['dashboard','Dashboard','Everyday','Safe-to-spend is first. The ring names its denominator; the breakdown explains the result.'],
 ['budget','Budget overview','Everyday','Allocation, used amounts and cash available have different meanings.'],
 ['category','Category detail','Everyday','A usage ring plus full amounts and category records.'],
 ['transactions','Transaction list','Everyday','Cash transactions and scanning are easy to reach.'],
 ['add','Add transaction','Everyday','A short form with account and category, then impact review.'],
 ['scan','Receipt camera','Receipts','Simulated camera. Clear framing guidance and import/manual alternatives.'],
 ['processing','Receipt processing','Receipts','Progress is explained; a cancelled scan remains a draft.'],
 ['review','Receipt review','Receipts','Questionable lines remain visible and editable. Confirmation precedes save.'],
 ['receipt','Receipt details','Receipts','Confirmed receipt links to the expense and price observations.'],
 ['product','Product history','Shopping','Every price is an observation, with date, size, currency and evidence.'],
 ['stores','Store comparison','Shopping','Dated branch comparisons; no claim about today’s cheapest store.'],
 ['lists','Shopping lists','Shopping','Plan before the purchase. Required and optional items remain distinct.'],
 ['list','Shopping list detail','Shopping','Quantities, pack sizes and price coverage stay visible.'],
 ['estimate','Shopping cost estimate','Shopping','Compare the estimate with grocery money and safe-to-spend independently.'],
 ['accounts','Accounts','Planning','Current liquid money is separated from protected savings. Advanced account types are Version 1.'],
 ['goals','Savings goals','Planning','A simple next contribution and meaningful progress.'],
 ['goal','Savings detail','Planning','Set aside, transferred and saved are distinguished.'],
 ['debts','Debt list','Planning','Version 1 concept. Minimum payments protect money in the pilot.'],
 ['debt','Debt detail','Planning','Version 1 concept. Payoff forecasts require explicit interest assumptions.'],
 ['reports','Reports','Explore','Charts always have amounts and a clear period. Transfers are excluded from spending.'],
 ['insights','Insights','Explore','Neutral explanations, with evidence and useful next actions.'],
 ['search','Search','Explore','Search on-device across receipts, products, records and lists.'],
 ['notifications','Notification settings','Settings','Control each alert and conceal money on the lockscreen by default.'],
 ['privacy','Privacy','Settings','Optional permissions, receipt retention and honest SDK disclosures.'],
 ['security','Security','Settings','Optional app lock and auto-lock, without claiming an untested security implementation.'],
 ['settings','General settings','Settings','The optional account and backup preference is visible here.'],
 ['data','Data export/delete','Settings','Preview scope before sharing, restoring or deleting. Cloud account and local data are separate.']
];
const priority = ['dashboard','payday','allocation','budget','scan','review','product','stores','estimate','goals','debt'];
const icons = {
 home:'M3 10l9-7 9 7v10H3z M9 20v-7h6v7', scan:'M8 3H3v5 M16 3h5v5 M3 16v5h5 M21 16v5h-5 M7 8h10v8H7z',
 plus:'M12 4v16 M4 12h16', plan:'M5 4h14v17H5z M8 8h8 M8 12h8 M8 16h5', shop:'M3 4h2l3 12h10l3-9H6 M9 20h.1 M18 20h.1',
 more:'M5 12h.1 M12 12h.1 M19 12h.1', transaction:'M4 7h15l-4-4 M20 17H5l4 4', bolt:'M13 2L5 14h7l-1 8 8-12h-7z',
 wifi:'M3 8a15 15 0 0118 0 M6 12a10 10 0 0112 0 M9 16a5 5 0 016 0 M12 20h.1', goal:'M12 3v3 M12 18v3 M3 12h3 M18 12h3 M12 7a5 5 0 100 10 5 5 0 000-10',
 receipt:'M5 3h14v18l-3-2-4 2-4-2-3 2z M8 7h8 M8 11h8 M8 15h5', arrow:'M5 12h14 M14 7l5 5-5 5', back:'M19 12H5 M10 7l-5 5 5 5', leaf:'M20 3C8 2 3 7 5 15s13 6 15-12z M5 20L15 9'
};
const icon = name => `<svg class="icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="${icons[name] || icons.plan}"/></svg>`;
const money = n => 'J$' + n.toLocaleString('en-JM');
const btn = (label,to,primary=false) => `<button class="${primary?'primary ':''}full" data-screen="${to}">${label}</button>`;
const head = (title,sub='',tag='') => `<div class="topline"><span class="overline">YardMoney</span>${tag?`<span class="pill">${tag}</span>`:''}</div><h2>${title}</h2>${sub?`<p>${sub}</p>`:''}`;
const step = n => `<div class="step" aria-label="Setup step ${n} of 5">${[1,2,3,4,5].map(i=>`<i class="${i<=n?'done':''}"></i>`).join('')}</div>`;
const ring = (pct,label,sub,colour='var(--needs)') => `<div class="ring" role="img" aria-label="${label} ${sub}; ${pct} percent"><svg viewBox="0 0 100 100" aria-hidden="true"><circle cx="50" cy="50" r="42" fill="none" stroke="var(--track)" stroke-width="8"/><circle cx="50" cy="50" r="42" fill="none" stroke="${colour}" stroke-width="8" stroke-dasharray="${Math.min(100,pct)*2.639} 264" stroke-linecap="round"/></svg><strong>${label}<small>${sub}</small></strong></div>`;
const donut = (distribution=false) => `<div class="ring" role="img" aria-label="${distribution?'Needs 73%, Wants 27%; J$37,400 spent':'Needs 50%, Wants 30%, Savings and debt 20%; J$82,000 allocated'}"><svg viewBox="0 0 100 100" aria-hidden="true"><circle cx="50" cy="50" r="40" fill="none" stroke="var(--needs)" stroke-width="10" stroke-dasharray="${distribution?183.47:125.66} 251.33"/><circle cx="50" cy="50" r="40" fill="none" stroke="var(--wants)" stroke-width="10" stroke-dasharray="${distribution?67.86:75.4} 251.33" stroke-dashoffset="${distribution?-183.47:-125.66}"/>${distribution?'':`<circle cx="50" cy="50" r="40" fill="none" stroke="var(--savings)" stroke-width="10" stroke-dasharray="50.27 251.33" stroke-dashoffset="-201.06"/>`}</svg><strong style="font-size:14px">${distribution?'J$37,400':'J$82,000'}<small>${distribution?'spent':'allocated'}</small></strong></div>`;
const legend = (name,amount,color='var(--needs)') => `<div class="legend-row"><span class="dot" style="background:${color}"></span><span>${name}</span><strong>${amount}</strong></div>`;
const row = (name,sub,value,ico='',to='') => `<div class="row"><div class="leading">${ico?`<span class="tile-icon">${icon(ico)}</span>`:''}<div><strong>${name}</strong><small>${sub}</small></div></div><div class="amount">${to?`<button class="text-button" data-screen="${to}">${value}</button>`:`<strong>${value}</strong>`}</div></div>`;
const progress = (pct,color='var(--needs)') => `<div class="progress" aria-hidden="true"><i style="width:${Math.min(100,pct)}%;background:${color}"></i></div>`;
const notice = (text,type='') => `<p class="notice ${type}">${text}</p>`;
const field = (label,value,type='text',id='field') => `<label class="form-label" for="${id}">${label}</label><input id="${id}" type="${type}" value="${value}">`;
const paper = () => `<div class="receipt-paper"><h4>MEGAMART</h4><p>Waterloo · St. Andrew<br>02 OCT 2026 · 10:24<br>FICTIONAL SAMPLE</p><hr><div class="receipt-line"><span>WHITE RICE 2KG</span><span>980.00</span></div><div class="receipt-line"><span>CHKN BRST 1KG</span><span>1950.00</span></div><div class="receipt-line"><span>EGGS 12 PACK</span><span>780.00</span></div><hr><div class="receipt-line"><b>TOTAL JMD</b><b>3710.00</b></div><p>THANK YOU</p></div>`;
const budgetCard = () => `<div class="card budget-layout">${donut()}<div class="legend">${legend('Needs · 50%','J$41,000')}${legend('Wants · 30%','J$24,600','var(--wants)')}${legend('Savings · 20%','J$16,400','var(--savings)')}</div></div>`;
const bills = () => row('Electricity','Due 5 Oct · reserved','J$7,500','bolt','bills')+row('Internet','Due 7 Oct · reserved','J$3,200','wifi','bills')+row('Water','Due 8 Oct · reserved','J$1,300','plan','bills');
const navItems = [['home','Home','dashboard'],['transaction','Transactions','transactions'],['plan','Plan','budget'],['shop','Shop','lists'],['more','More','settings']];
let current='dashboard', scenario='normal', rebalancePreview=null;
let galleryOpen=false;
function screenContent(id){
 switch(id){
 case 'splash': return `<div class="empty-art" style="padding-top:150px"><span class="brand-mark" style="margin:auto;width:76px;height:76px;font-size:44px">Y</span><h2>YardMoney</h2><p>Make room for what matters.</p>${btn('View welcome','welcome',true)}</div>`;
 case 'welcome': return `${head('Your money.<br>Your next move.','A calmer way to plan life between paydays.')}<div class="intro-art">${ring(72,'J$','your way')}<div class="floating">Bills covered. Breathe easier.</div></div><div class="center-title"><h2>One payday at a time.</h2><p>Know what’s safe to spend, plan your shopping and remember what things cost.</p></div>${btn('Let’s get started','initial',true)}${notice('No account needed to budget. Optional account and backup available in Version 1.')}`;
 case 'initial': return `${head('Make yourself at home','Just a few essentials. You can change these later.')}${step(1)}<label class="form-label" for="currency">Your main currency</label><select id="currency"><option>JMD · Jamaican Dollar (J$)</option><option>USD · US Dollar (US$)</option><option>CAD · Canadian Dollar</option><option>GBP · Pound Sterling</option><option>EUR · Euro</option></select>${field('What should we call you? (optional)','Geovanni','text','nickname')}${notice('Sample review uses JMD. Other currencies remain separate; no automatic conversion.')}${btn('Continue','payday',true)}<p class="help">Core use stays local. You can choose an optional account and backup later.</p>`;
 case 'payday': return `${head('When do you get paid?','Your budget should follow your life, not the calendar.')}${step(2)}${['Weekly','Every 2 weeks','Twice monthly','Monthly','Irregular / freelance','Custom schedule'].map((s,i)=>`<button class="choice ${i===1?'selected':''}" data-choice="schedule" aria-pressed="${i===1}">${s}<span>${i===1?'✓':'○'}</span></button>`).join('')}${notice('Every 2 weeks = every 14 days. Twice monthly = two dates you choose.')}${btn('Continue','next',true)}`;
 case 'next': return `${head('Your next payday','Choose the date your money normally arrives.')}${step(2)}${field('Next payday','2026-10-09','date','paydate')}<div class="card"><div class="big-date">9 October</div><p class="mini-center">Friday · 7 days from the sample date</p></div>${notice('For irregular income, use a planning date. We won’t assume the money has arrived.')}${btn('Continue','income',true)}`;
 case 'income': return `${head('What reaches your pocket?','Use your take-home pay, after deductions.')}${step(3)}${field('Typical take-home pay · J$','82000','text','netpay')}<label class="check"><input type="checkbox">My income changes each period</label><label class="form-label" for="basis">Planning basis</label><select id="basis"><option>Manually entered take-home pay</option><option>Conservative expected income</option><option>Average recent income</option><option>Minimum recent income</option></select>${notice('Expected income is a plan, not spendable cash. Add received pay to an account when it arrives.')}${btn('Continue','allocation',true)}<p class="help">Gross-pay estimates come later, after Jamaican payroll rules are verified.</p>`;
 case 'allocation': return `${head('Give your payday a plan','50/30/20 is a starting point. Make it fit you.')}${step(4)}${budgetCard()}<div class="card">${row('Needs','Bills, groceries and everyday essentials','50%')}${row('Wants','Enjoyment and optional spending','30%')}${row('Savings / debt','Goals and extra debt payments','20%')}</div>${btn('Use 50 / 30 / 20','bills',true)}${btn('Choose my own percentages','custom')}<p class="help">Minimum debt payments belong under Needs. You can reclassify categories.</p>`;
 case 'custom': return `${head('Make the split yours','Choose what works for this pay period.')}<h3>Take-home pay · J$82,000</h3><div class="split-inputs">${[['Needs',60],['Wants',25],['Savings',20]].map(([s,v],i)=>`<label for="pct${i}">${s} %<input id="pct${i}" type="number" min="0" max="100" step="1" value="${v}" aria-describedby="allocation-status"></label>`).join('')}</div><div id="allocation-status" role="status" aria-live="polite">${notice('Your budget totals 105%. Reduce one or more categories by 5%.','error')}</div><button class="full" id="rebalance">Preview auto-rebalance</button><div id="rebalance-preview" hidden></div><button class="primary full" id="save-allocation" disabled>Use this split</button>${notice('Your split must total exactly 100%. Rebalancing changes are shown before you accept them.')}`;
 case 'bills': return `${head('Protect the essentials','What needs paying before your next payday?','Optional')}<div class="card">${bills()}</div>${notice('Proposed default: unpaid bills reserve money automatically. Review the breakdown and change reservations whenever needed.')}${btn('Continue with these sample bills','dashboard',true)}${btn('Set up later','dashboard')}<p class="help">Next in the app: enter current account balances. Typical pay is not your current balance.</p>`;
 case 'dashboard': return `<div class="topline"><div><span class="overline">FRIDAY, 2 OCTOBER</span><h2>Morning, Geovanni</h2></div><span class="avatar" aria-label="Geovanni profile">G</span></div><div class="topline"><p>Next payday <strong>Fri, 9 Oct</strong></p><span class="pill">7 days to go</span></div><div class="hero"><h3>Safe to spend until payday</h3><div class="hero-ring"><div class="safe-text"><div class="money">J$18,420</div><p>J$2,631/day · guidance, not a target</p></div>${ring(44,'44%','of funds','#b9dcc7')}</div><div class="hero-foot"><span>J$23,580 protected</span><button data-explain>See breakdown</button></div></div><div id="breakdown" hidden class="card">${row('Included funds','Cash, current account and wallet','J$42,000')}${row('Unpaid bills','Due before payday','− J$12,000')}${row('Savings commitment','Still in included accounts','− J$8,000')}${row('Minimum debt','Not also counted as a bill','− J$3,580')}${row('Safe to spend','Balances last confirmed 2 Oct','J$18,420')}</div><div class="actions"><button class="primary" data-screen="scan">${icon('scan')}Scan receipt</button><button data-screen="add">${icon('plus')}Add expense</button></div><div class="section-head"><h3>Your payday plan</h3><button class="text-button" data-screen="budget">View plan →</button></div>${budgetCard()}<div class="section-head"><h3>Coming up</h3><span class="pill">Covered</span></div>${bills()}<p class="sample-tag">Fictional sample · JMD · Manual accounts</p>`;
 case 'budget': return `${head('Your payday plan','25 Sep – 8 Oct 2026 · next payday 9 Oct')}<div class="section-head"><h3>50 / 30 / 20</h3><button class="text-button" data-screen="custom">Edit split</button></div>${budgetCard()}${[['Needs',27400,41000,'var(--needs)'],['Wants',10000,24600,'var(--wants)'],['Savings / extra debt',8000,16400,'var(--savings)']].map(([n,v,t,c])=>`<div class="card"><div class="topline"><strong>${n}</strong><span class="pill">${money(t-v)} left</span></div>${progress(Math.round(v/t*100),c)}<p>${money(v)} ${n.startsWith('Savings')?'fulfilled':'spent'} of ${money(t)}</p></div>`).join('')}${btn('Explore groceries','category')}<h3>Planned vs actual progress</h3><p class="help">Plan target / spent or fulfilled · this period</p>${[['Needs',41000,27400],['Wants',24600,10000],['Savings',16400,8000]].map(([n,p,a])=>`<div class="bar-row"><header><span>${n}</span><span>${money(p)} / ${money(a)}</span></header><div class="paired-bars"><span><i style="width:${p/410}%"></i></span><span><i style="width:${a/410}%"></i></span></div></div>`).join('')}`;
 case 'category': return `${head('Groceries','Needs · 25 Sep – 8 Oct')}<div class="card budget-layout">${ring(68,'68%','used')}<div><div class="overline">REMAINING</div><h2>J$6,400</h2><p>J$13,600 spent of J$20,000</p></div></div>${btn('Plan a shopping list','list',true)}<h3>Recent groceries</h3>${row('MegaMart · Waterloo','2 Oct · receipt reviewed','J$3,710','receipt','receipt')}${row('Market produce','30 Sep · cash','J$2,400','shop')}${row('Other groceries','Earlier this period','J$7,490','shop')}`;
 case 'transactions': return `${head('Your activity','Every money move, in one place.')}<div class="actions"><button class="primary" data-screen="scan">${icon('scan')}Scan receipt</button><button data-screen="add">${icon('plus')}Add</button></div><label class="form-label" for="filter">Show</label><select id="filter"><option>All transactions</option><option>Expenses</option><option>Income</option><option>Transfers</option><option>Refunds</option></select><h3>Today · 2 October</h3>${row('MegaMart · Waterloo','Groceries · current account','− J$3,710','receipt','receipt')}${row('Taxi fare','Transport · cash','− J$250','transaction')}<h3>25 September</h3>${row('Salary received','Income · current account','+ J$82,000','transaction')}${row('Emergency fund transfer','Transfer · not an expense','J$8,000','goal','goal')}`;
 case 'add': return `${head('Add a money move','A little detail now. A clearer plan later.')}<label class="form-label" for="type">Type</label><select id="type"><option>Expense</option><option>Income</option><option>Transfer</option><option>Refund</option><option>Adjustment</option></select>${field('Amount · J$','250','text','amount')}<label class="form-label" for="account">From account</label><select id="account"><option>Cash · J$4,000 available</option><option>Current account</option><option>Mobile wallet</option></select><label class="form-label" for="category">Category</label><select id="category"><option>Transport · Needs</option><option>Groceries · Needs</option><option>Dining · Wants</option></select>${field('Description (optional)','Taxi fare','text','description')}${notice('Sample preview: safe-to-spend would become J$18,170. No record will be saved.')}<button class="primary full" data-demo="Expense reviewed. This design prototype saves no financial data.">Review expense</button>${btn('Attach a receipt','scan')}`;
 case 'scan': return `${head('Scan a receipt','Keep the whole receipt inside the frame.','On-device')}<div class="camera">${paper()}</div>${notice('Sample camera view. In the app: avoid glare and keep the bottom total visible.')}<button class="capture" data-screen="processing" aria-label="Capture sample receipt"></button><div class="actions"><button data-demo="The app will use Android’s photo picker. This prototype does not import images.">Import photo</button><button data-screen="add">Enter manually</button></div><p class="sample-tag">SIMULATED CAMERA · No permission requested</p>`;
 case 'processing': return `${head('Reading your receipt','Your review comes next. Nothing saved yet.')}<div class="loader" aria-hidden="true"></div><div class="mini-center"><h3>Finding the items…</h3><p>Capture ✓ &nbsp; Text ✓ &nbsp; Checking totals</p></div><div class="card">${row('Receipt captured','Image stays on your device','✓')}${row('Merchant found','MegaMart · Waterloo','✓')}${row('One item needs a check','We’ll highlight it next','!')}</div>${btn('View sample results','review',true)}${btn('Cancel and keep draft','transactions')}`;
 case 'review': return `${head('A quick check before saving','MegaMart · Waterloo · 2 Oct 2026','1 to check')}${notice('“CHKN BRST 1KG” needs checking. Confirm the item and price against the receipt.','warn')}<div class="card">${row('White rice · 2 kg','1 pack × J$980 · High confidence','J$980')}<div style="border:1px solid var(--wants);padding:12px;border-radius:12px;margin:10px 0"><span class="pill">! Needs checking</span>${field('Item name','Chicken breast · 1 kg','text','chicken-name')}${field('Line price · J$','1950','text','chicken-price')}<label class="check"><input type="checkbox" id="confirm-line">I checked this item against the receipt</label></div>${row('Eggs · 12 pack','1 pack × J$780 · High confidence','J$780')}</div><div class="card">${row('Items total','No separate tax amount shown','J$3,710')}${row('Receipt total','Matches the items','J$3,710')}</div><button id="confirm-receipt" class="primary full" disabled>Confirm and save · J$3,710</button>${btn('View receipt image','receipt')}<p class="help">In the app, confirm the account and check for duplicates before posting. No silent saves.</p>`;
 case 'receipt': return `${head('Receipt details','MegaMart · Waterloo · St. Andrew','Reviewed')}<div class="camera" style="min-height:280px">${paper()}</div><div class="card">${row('Total paid','2 Oct 2026 · 10:24 · JMD','J$3,710')}${row('Paid from','Current account · sample record','Manual')}${row('Confirmed items','Three personal price observations','3')}</div>${btn('See rice price history','product',true)}${btn('Review items','review')}`;
 case 'product': return `${head('White rice','Sample brand · 2 kg · JMD','Your receipts')}<div class="hero"><div class="overline">LAST OBSERVED</div><div class="money">J$980</div><p>2 Oct 2026 · MegaMart, Waterloo</p><div class="hero-foot"><span>J$490/kg</span><span>7 sample observations</span></div></div><h3>Your price history</h3><p class="help">Pack prices across your recorded branches</p><svg class="line-chart" viewBox="0 0 330 155" role="img" aria-label="April J$910, May 850, June 850, July 890, August 930, September 900, October 980"><path d="M35 20H315 M35 65H315 M35 110H315" stroke="var(--line)"/><text x="0" y="24" fill="currentColor">1,000</text><text x="8" y="69" fill="currentColor">900</text><text x="8" y="114" fill="currentColor">800</text><polyline points="40,61 85,88 130,88 175,70 220,52 265,65 310,29" fill="none" stroke="var(--primary)" stroke-width="3"/>${[[40,61],[85,88],[130,88],[175,70],[220,52],[265,65],[310,29]].map(([x,y])=>`<circle cx="${x}" cy="${y}" r="4" fill="var(--primary)"/>`).join('')}<text x="35" y="140" fill="currentColor">Apr</text><text x="165" y="140" fill="currentColor">Jul</text><text x="290" y="140" fill="currentColor">Oct</text></svg><div class="stat-grid"><div class="stat"><small>Lowest observed</small><strong>J$850</strong></div><div class="stat"><small>Highest observed</small><strong>J$980</strong></div><div class="stat"><small>Average · 7 prices</small><strong>J$901.43</strong></div><div class="stat"><small>Since last observation</small><strong>+ J$80</strong></div></div>${notice('These are your past purchases, not today’s store prices.')}${btn('Compare recorded branches','stores',true)}<details><summary>View price data</summary>${[['3 Apr',910],['8 May',850],['5 Jun',850],['10 Jul',890],['7 Aug',930],['4 Sep',900],['2 Oct',980]].map(([d,p])=>row(d+' 2026','Fictional receipt observation',money(p))).join('')}</details>`;
 case 'stores': return `${head('Where you saw it','White rice · same sample brand · 2 kg · JMD')}<span class="pill">Last 30 days · exact product</span>${[['Progressive · Portmore',920,'22 Sep · St. Catherine'],['MegaMart · Waterloo',980,'2 Oct · St. Andrew'],['Hi-Lo · Liguanea',995,'29 Sep · St. Andrew']].map(([n,p,d],i)=>`<div class="bar-row"><header><strong>${n}</strong><strong>${money(p)}</strong></header>${progress(Math.round(p/10.5),i===0?'var(--needs)':'var(--savings)')}<small>${d} · ${money(p/2)}/kg${i===0?' · lowest observed in this range':''}</small></div>`).join('')}${notice('Different observation dates. Price and availability may have changed. Travel costs are not included.','warn')}<div class="card">${row('Older observation','Sample branch · 3 May · excluded from recent range','J$880') }</div>${btn('Add rice to shopping list','list',true)}<p class="sample-tag">FICTIONAL PRICES · Not merchant quotes</p>`;
 case 'lists': return `${head('Shop with a plan','A little preparation goes a long way.')}<div class="card"><span class="pill">7 items · 1 stale price</span><h2>Weekend groceries</h2><p>Preferred branch: MegaMart · Waterloo</p><div class="money" style="font-size:30px">~ J$5,800</div>${btn('Open shopping list','list',true)}</div><div class="card"><h3 style="margin-top:0">Household essentials</h3><p>3 items · prices needed</p>${btn('View unknown-price example','estimate')}</div><button class="full" data-demo="New-list form would ask for a name and optional preferred branch.">${icon('plus')}Create a list</button>`;
 case 'list': return `${head('Weekend groceries','MegaMart · Waterloo · fictional estimate')}<span class="pill">6 recent · 1 stale · 0 missing</span>${[['White rice · 2 kg',980],['Chicken breast · 1 kg',1950],['Eggs · 12 pack',780],['Milk · 1 L',450],['Bread · 1 loaf',500],['Cooking oil · 1 L',690],['Toilet tissue · 4 pack',450]].map(([n,p],i)=>`<div class="row"><label class="check" style="margin:0"><input type="checkbox"><span><strong>${n}</strong><small>Quantity 1 · ${i===5?'Stale: 12 Aug':'Recent sample receipt'} · ${i===6?'Optional':'Required'}</small></span></label><strong>${money(p)}</strong></div>`).join('')}${notice('Checking an item means picked up. It does not save an expense.')}${btn('Check my shopping estimate','estimate',true)}`;
 case 'estimate': return `${head('Can this list fit?','Weekend groceries · preferred-branch estimate')}<div class="card budget-layout">${ring(91,'91%','of groceries')}<div><div class="overline">ESTIMATED TOTAL</div><h2>J$5,800</h2><p>Indicative range<br>J$5,450–J$6,350</p></div></div>${notice('6 recent prices, 1 stale price, 0 missing. Range uses sample observations/assumptions; prices can change.','warn')}<div class="card">${row('Grocery money remaining','Current category budget','J$6,400')}${row('After this list','At the central estimate','J$600')}${row('Safe-to-spend after purchase','Different from grocery money','J$12,620')}</div><div class="card"><h3 style="margin:0 0 8px">A little breathing room</h3><p>At the high estimate, groceries would have J$50 left. Check the stale oil price before shopping.</p></div>${btn('Review my list','list',true)}<button class="full" data-unknown>Show missing-price example</button><div id="unknown-price" hidden>${notice('1 item has no price. Known subtotal: J$5,110. Add an oil estimate to get a complete list total.','warn')}</div>`;
 case 'accounts': return `${head('Your accounts','Manual balances · confirmed 2 Oct 2026')}<div class="hero"><div class="overline">INCLUDED LIQUID FUNDS</div><div class="money">J$42,000</div><p>Before bills and commitments</p></div>${row('Current account','Included · manual','J$35,000','transaction')}${row('Cash','Included · manual','J$4,000','transaction')}${row('Mobile wallet','Included · manual','J$3,000','transaction')}${row('Emergency savings','Protected · excluded from spendable pool','J$126,000','goal','goal')}${notice('Version 1 adds full credit-card, loan and investment account support. Credit limits never count as spendable money.')}<button class="full" data-demo="Adding an account requires type, currency and confirmed opening balance.">Add an account</button>`;
 case 'goals': return `${head('Make room for your goals','Small steps count.')}<div class="card"><div class="topline"><span class="tile-icon">${icon('goal')}</span><span class="pill">42% saved</span></div><h3>Emergency fund</h3><div class="budget-layout">${ring(42,'42%','saved','var(--savings)')}<div><h2>J$126,000</h2><p>of J$300,000</p></div></div>${btn('View goal','goal',true)}</div><div class="card"><h3 style="margin-top:0">School fees</h3>${progress(30,'var(--savings)')}<p>J$18,000 of J$60,000 · 30% saved</p></div><button class="full" data-demo="Goal setup: name, target amount and optional date/account.">${icon('plus')}Create a goal</button>`;
 case 'goal': return `${head('Emergency fund','A cushion for the unexpected.')}<div class="card budget-layout">${ring(42,'42%','saved','var(--savings)')}<div><h2>J$126,000</h2><p>J$174,000 to your target</p></div></div><div class="card">${row('Saved in protected account','Already excluded from available money','J$126,000')}${row('This period’s next commitment','Reserved, not yet transferred','J$8,000')}</div>${notice('Setting money aside does not move money at your bank. Record the transfer after it happens.')}<button class="primary full" data-demo="The app will review the source/destination accounts before recording a transfer.">Record a contribution</button><h3>Recent contribution</h3>${row('25 Sep 2026','Sample transfer · included in saved total','J$8,000','goal')}`;
 case 'debts': return `${head('Your debt plan','Version 1 concept · manual tracking')}<div class="hero"><div class="overline">TOTAL REMAINING</div><div class="money">J$180,000</div><p>One sample personal loan</p></div><div class="card"><h3 style="margin-top:0">Personal loan</h3>${progress(40,'var(--savings)')}<p>J$120,000 repaid · J$180,000 remaining</p>${row('Next minimum','6 Oct · reserved once under Needs','J$3,580')}${btn('View repayment details','debt',true)}</div>${notice('Minimum payments can be tracked as bills in the pilot. Advanced debt calculations follow later.')}`;
 case 'debt': return `${head('Personal loan','Version 1 design · balances entered manually')}<div class="card"><div class="overline">BALANCE TO REPAY</div><div class="money">J$180,000</div>${progress(40,'var(--savings)')}<p>40% repaid · J$120,000 of J$300,000 original</p></div><div class="card">${row('Next minimum payment','6 Oct · protected under Needs','J$3,580')}${row('Extra repayment','Savings / debt bucket','Not set')}${row('Interest rate','Needed for an accurate scenario','Unknown')}</div>${notice('No payoff date shown: the interest and fee assumptions are unknown. Minimum payment is already reserved, not counted again.')}<button class="primary full" data-demo="In Version 1, link an existing payment or review a new record.">Record a payment</button>${btn('View all debts','debts')}`;
 case 'reports': return `${head('See the bigger picture','25 Sep – 8 Oct 2026 · sample period')}<h3>Spending distribution</h3><div class="card budget-layout">${donut(true)}<div class="legend">${legend('Needs · 73.3%','J$27,400')}${legend('Wants · 26.7%','J$10,000','var(--wants)')}</div></div><p class="help">Total expenses J$37,400. Savings transfers and account transfers excluded.</p><h3>Period comparison</h3><div class="card">${row('Previous 14-day period','Sample spend · J$3,200/day','J$44,800')}${row('Current period so far','8 completed days · J$4,675/day','J$37,400')}</div>${notice('Current period is incomplete. Daily spending is J$1,475 higher; total-period comparison would be misleading.')}${btn('Explore insights','insights',true)}`;
 case 'insights': return `${head('A few useful clues','Evidence, not judgement.')}<div class="card"><span class="pill">Shopping</span><h3>Rice has changed</h3><p>Your sample pack was J$900 in September and J$980 on 2 October. That is J$80 more per 2 kg pack.</p>${btn('View the observations','product')}</div><div class="card"><span class="pill">Payday planning</span><h3>Bills have room in your plan</h3><p>J$12,000 is reserved for three unpaid bills before payday. Check variable bills when the actual amount arrives.</p>${btn('Review bills','bills')}</div>`;
 case 'search': return `${head('Find your money story','Search only the data on your device.')}<label class="form-label" for="query">Search records, products and lists</label><input class="search-field" id="query" type="search" value="rice"><div id="search-results"><h3>Products</h3>${row('White rice · 2 kg','7 sample observations · last 2 Oct','J$980','shop','product')}<h3>Receipts</h3>${row('MegaMart · Waterloo','2 Oct · rice, chicken and eggs','View','receipt','receipt')}</div>`;
 case 'notifications': return `${head('Helpful reminders','Choose what deserves your attention.')}<div class="card toggle-row">${[['Payday',true],['Bills due',true],['Budget running low',false],['Savings reminders',false],['Shopping estimate over budget',true],['Show amounts on lockscreen',false]].map(([n,c],i)=>`<div class="row"><label for="notify${i}">${n}<input id="notify${i}" type="checkbox" ${c?'checked':''}></label></div>`).join('')}</div>${notice('In the app, enable notifications to receive reminders. Delivery can be delayed by Android; check due dates in Plan.')}`;
 case 'privacy': return `${head('Your data, your say','Keep only what is useful to you.')}<div class="card toggle-row"><div class="row"><label for="location">Optional branch location<input id="location" type="checkbox"></label></div><div class="row"><strong>Added analytics</strong><span class="pill">None proposed</span></div></div><label class="form-label" for="images">After receipt confirmation</label><select id="images"><option>Keep compressed receipt image</option><option>Keep original image</option><option>Delete image after extraction</option></select>${notice('Receipt text is read on-device. ML Kit documentation describes SDK diagnostic metrics; final disclosures depend on the selected SDK audit.')}${btn('Manage exports and backups','data',true)}<p class="help">No public receipt sharing. The app works without location.</p>`;
 case 'security': return `${head('A little extra protection','Choose an app lock that works for you.')}<div class="card toggle-row"><div class="row"><label for="applock">App lock<input id="applock" type="checkbox" checked></label></div><div class="row"><label for="biometric">Biometric unlock<input id="biometric" type="checkbox" checked></label></div></div><label class="form-label" for="autolock">Lock after inactivity</label><select id="autolock"><option>1 minute</option><option>Immediately</option><option>5 minutes</option></select>${notice('Production security and fallback recovery must be tested on Android. These controls are design examples.')}`;
 case 'settings': return `${head('Make it yours','Your preferences and your data.')}<div class="card"><h3 style="margin-top:0">Optional account & backup</h3><p>Keep budgeting without signing in. Choose encrypted backup when you want recovery across devices.</p><button class="full" data-backup>Explore optional backup</button><div id="backup-info" hidden>${notice('Version 1 proposal: choose an account, protect your backup with a recovery secret, and select whether images are included. Provider, region, recovery and costs must be reviewed first.')}</div></div>${row('Currency & pay schedule','JMD · every 2 weeks','Edit','plan','payday')}${row('Budget method','50 / 30 / 20','Edit','plan','allocation')}${row('Notifications','Bills and payday','Open','plan','notifications')}${row('Privacy','Images, location and disclosures','Open','plan','privacy')}${row('Security','App lock and auto-lock','Open','plan','security')}${row('Accounts','Cash, bank, wallet and savings','Open','transaction','accounts')}${row('Reports & insights','Understand your spending','Open','plan','reports')}${row('Search','Find records and prices','Open','shop','search')}${row('Data & backup','Export, restore and delete','Open','plan','data')}`;
 case 'data': return `${head('Your data travels with you','Export carefully. Keep a recoverable backup.')}<div class="card"><h3 style="margin-top:0">Encrypted backup</h3><p>Local backup in the pilot. Optional account and cloud backup in Version 1. A recovery secret protects portable copies.</p><button class="primary full" data-demo="Backup preview would show included records, image choice and recovery checks. No backup created here.">Preview backup</button></div><button class="full" data-demo="CSV export preview: scope, currency, dates and identifier redaction. No file exported here.">Preview CSV export</button><button class="full" data-demo="Restore previews the version, integrity and replacement scope before any write.">Review restore options</button>${notice('Deleting app data does not delete files you already exported. Local wipe and remote account/backup deletion are separate choices.','warn')}<details><summary style="color:var(--danger);padding:15px 0">Delete local data</summary><p class="help">Production will require explicit confirmation. This prototype contains no stored financial data.</p><button class="full" data-demo="Design preview only. No financial records exist to delete.">Preview deletion scope</button></details>`;
 default:return head('Screen unavailable');
 }
}
function stateContent(id){
 if(scenario==='empty')return `${head('A fresh start','No '+(id==='lists'?'shopping lists':'records')+' yet.')}<div class="empty-art"><div class="tile-icon">${icon('receipt')}</div><h3>Your next step is a small one.</h3><p>Scan your first receipt to start building your personal price history.</p>${btn('Scan my first receipt','scan',true)}${btn('Add something manually','add')}</div>`;
 if(scenario==='loading')return screenContent('processing');
 if(scenario==='error')return `${head('Let’s try that again','Your draft is still here. Nothing was saved.')}<div class="empty-art"><div class="tile-icon">!</div><h3>The receipt wasn’t clear enough</h3><p>The bottom total may be missing. Retake the photo with the full receipt in view, or enter the amount yourself.</p>${btn('Retake receipt','scan',true)}${btn('Enter manually','add')}</div>`;
 if(scenario==='low')return screenContent('review');
 if(scenario==='exceeded')return `${head('Your plan has changed','Spending over a target can happen.')}<div class="card">${ring(110,'110%','of target','var(--danger)')}<h3>Wants · J$2,400 over target</h3><p>J$26,400 spent against a J$24,000 scenario target.</p></div>${notice('You can still record the expense. Moving budget targets does not create more cash.','warn')}${btn('Move money from another bucket','custom',true)}<button class="full" data-demo="In the app, continue records a valid expense despite the warning.">Continue anyway</button>${btn('Cancel','dashboard')}`;
 return (scenario==='offline'?notice('Offline · local records and bundled OCR still work. Optional cloud backup will wait for a connection.'):'')+screenContent(id);
}
function nav(id){let active=['splash','welcome','initial','payday','next','income','allocation','custom','bills'].includes(id)?'':(['transactions','add','scan','processing','review','receipt'].includes(id)?'transactions':(['budget','category','goals','goal','debts','debt'].includes(id)?'budget':(['product','stores','lists','list','estimate'].includes(id)?'lists':(['accounts','reports','insights','search','notifications','privacy','security','settings','data'].includes(id)?'settings':'dashboard'))));return navItems.map(([ico,n,to])=>`<button class="${active===to?'active':''}" data-screen="${to}" ${active===to?'aria-current="page"':''}>${icon(ico)}${n}</button>`).join('');}
function show(id,updateHash=true){current=screens.some(s=>s[0]===id)?id:'dashboard';const s=screens.find(s=>s[0]===current);document.getElementById('content').innerHTML=stateContent(current);document.getElementById('content').scrollTop=0;document.getElementById('bottom-nav').innerHTML=nav(current);document.getElementById('screens').value=current;document.getElementById('screen-number').textContent=`${String(screens.indexOf(s)+1).padStart(2,'0')} / 36`;document.getElementById('note-title').textContent=s[1];document.getElementById('note').textContent=s[3];document.querySelectorAll('#screen-links button').forEach(b=>b.classList.toggle('active',b.dataset.screen===current));if(updateHash)history.replaceState(null,'','#'+current);}
function toast(text){const t=document.getElementById('toast');t.textContent=text;t.hidden=false;clearTimeout(toast.timer);toast.timer=setTimeout(()=>t.hidden=true,6000);}
function checkAllocation(){const vals=[0,1,2].map(i=>document.getElementById('pct'+i)?.value);if(vals.some(v=>v===undefined))return;const valid=vals.every(v=>/^\d+$/.test(v)&&Number(v)<=100);const total=valid?vals.reduce((sum,v)=>sum+Number(v),0):null;document.getElementById('save-allocation').disabled=total!==100;document.getElementById('allocation-status').innerHTML=notice(!valid?'Enter whole percentages from 0 to 100.':total===100?'Your budget totals 100%. Ready to use.':`Your budget totals ${total}%. ${total>100?'Reduce':'Increase'} one or more categories by ${Math.abs(100-total)}%.`,total===100?'':'error');rebalancePreview=null;document.getElementById('rebalance-preview').hidden=true;}
function gallery(){document.getElementById('workspace').hidden=galleryOpen;document.getElementById('gallery').hidden=!galleryOpen;document.getElementById('board').textContent=galleryOpen?'Single screen':'Screen gallery';document.getElementById('board').setAttribute('aria-pressed',String(galleryOpen));if(galleryOpen)document.getElementById('gallery').innerHTML=priority.map(id=>{const s=screens.find(s=>s[0]===id);return `<figure><figcaption>${s[1]}</figcaption><article class="phone"><div class="statusbar"><span>9:41</span><span>▮▮▮ ◔ ▰</span></div><div class="phone-content">${screenContent(id).replace(/\bid="/g,`id="gallery-${id}-`).replace(/\bfor="/g,`for="gallery-${id}-`).replace(/<button/g,'<button disabled').replace(/<input/g,'<input disabled').replace(/<select/g,'<select disabled')}</div><div class="bottom-nav">${nav(id)}</div><div class="gesture"></div></article><p>${s[3]}</p></figure>`}).join('');}
const links=document.getElementById('screen-links');let group='';screens.forEach(([id,name,g])=>{const opt=document.createElement('option');opt.value=id;opt.textContent=name;document.getElementById('screens').append(opt);if(g!==group){const h=document.createElement('div');h.className='group';h.textContent=g.toUpperCase();links.append(h);group=g;}const b=document.createElement('button');b.dataset.screen=id;b.textContent=name;links.append(b);});
document.addEventListener('click',event=>{const b=event.target.closest('button');if(!b)return;if(b.dataset.screen){scenario='normal';document.getElementById('state').value=scenario;show(b.dataset.screen);document.getElementById('phone').focus({preventScroll:true});}else if(b.dataset.demo)toast(b.dataset.demo);else if(b.hasAttribute('data-choice')){document.querySelectorAll(`[data-choice="${b.dataset.choice}"]`).forEach(c=>{c.classList.toggle('selected',c===b);c.setAttribute('aria-pressed',String(c===b));c.querySelector('span').textContent=c===b?'✓':'○';});toast('Schedule choice shown. Dates in this prototype remain fictional.');}else if(b.hasAttribute('data-explain')){const panel=document.getElementById('breakdown');panel.hidden=!panel.hidden;b.setAttribute('aria-expanded',String(!panel.hidden));}else if(b.hasAttribute('data-unknown'))document.getElementById('unknown-price').hidden=false;else if(b.hasAttribute('data-backup'))document.getElementById('backup-info').hidden=false;else if(b.id==='confirm-receipt'){toast('Sample receipt confirmed. Production would check duplicates and save atomically; nothing is stored here.');show('receipt');}else if(b.id==='save-allocation'){toast('Valid sample allocation selected. No budget saved.');show('budget');}else if(b.id==='rebalance'){const vals=[0,1,2].map(i=>Number(document.getElementById('pct'+i).value));if(vals.some(v=>!Number.isInteger(v)||v<0||v>100)||vals.reduce((s,v)=>s+v,0)===0){toast('Enter valid percentages with at least one value above zero.');return;}const total=vals.reduce((s,v)=>s+v,0),scaled=vals.map(v=>v*100/total),base=scaled.map(Math.floor);let remainder=100-base.reduce((s,v)=>s+v,0);scaled.map((v,i)=>({i,f:v-base[i]})).sort((a,b)=>b.f-a.f||a.i-b.i).slice(0,remainder).forEach(v=>base[v.i]++);rebalancePreview=base;const preview=document.getElementById('rebalance-preview');preview.hidden=false;preview.innerHTML=notice(`Preview: Needs ${base[0]}%, Wants ${base[1]}%, Savings ${base[2]}%. Total 100%.`)+'<button class="full" id="accept-rebalance">Accept rebalanced percentages</button>';}else if(b.id==='accept-rebalance'&&rebalancePreview){rebalancePreview.forEach((v,i)=>document.getElementById('pct'+i).value=v);checkAllocation();}});
document.addEventListener('input',e=>{if(/^pct\d$/.test(e.target.id))checkAllocation();if(e.target.id==='confirm-line')document.getElementById('confirm-receipt').disabled=!e.target.checked;if(e.target.id==='query'){const q=e.target.value.toLowerCase().trim();document.getElementById('search-results').innerHTML=q&&'rice'.includes(q)?`<h3>Products</h3>${row('White rice · 2 kg','7 sample observations','J$980','shop','product')}`:notice('No sample results. Try “rice”.');}if(e.target.id==='chicken-name'||e.target.id==='chicken-price'){document.getElementById('confirm-line').checked=false;document.getElementById('confirm-receipt').disabled=true;document.getElementById('confirm-receipt').textContent='Review changed values before saving';}});
document.getElementById('screens').addEventListener('change',e=>{scenario='normal';document.getElementById('state').value='normal';show(e.target.value);});
document.getElementById('state').addEventListener('change',e=>{scenario=e.target.value;show(current);});
document.getElementById('theme').addEventListener('click',e=>{const dark=document.body.classList.toggle('dark');e.target.textContent=dark?'Light mode':'Dark mode';e.target.setAttribute('aria-pressed',String(dark));});
document.getElementById('palette').addEventListener('change',e=>document.body.classList.toggle('harbour',e.target.value==='harbour'));
document.getElementById('board').addEventListener('click',()=>{galleryOpen=!galleryOpen;gallery();});
window.addEventListener('hashchange',()=>show(location.hash.slice(1),false));
show(location.hash.slice(1)||'dashboard',false);
